### ISSUE TITLE
Closures should be passed as trait `FnMut` instead of `Fn`

### ISSUE THREAD

**Issue by benjamin-cates** [AzeezDa/eqsolver#5]
Hello! I was using this crate to solve a system of equations and kept hitting max iterations reached (it ended up being a precision limitation on my part). During this issue, I tried to add logging (pushing to a vector to do numerical analysis) to my function closure, but the compiler wasn't allowing it because the struct takes `impl Fn` (can be called any number of times on different threads) instead of `impl FnMut` (can be called any number of times on a single thread). Besides my use case there also might be other reasons for requiring `FnMut` like functions that need memoization for stuff like factorials. I think that since solving equations via iterative methods has to be single threaded, that is should allow functions that mutate their environment. I would be willing to submit a pull request/work with you further. Thanks for your time!

**Comment by AzeezDa** [comment]
Hi, @benjamin-cates! Thank you for the suggestion! I think it is a very plausible addition to the library. However, my only concern is that making the function `FnMut` might cause unpredictable behaviours if not used cautiously. This is because the number of times the to-be-solved function is called is unknown to the user and thus might mutate the environment in an unknown manner. This is why I feel that `Fn` give better safety than `FnMut`. That aside, I think this suggestion can be added as a feature, i.e. by marking the dependency with `features = ["mutable-closures"]` or something of that sort to enable `FnMut` for the closures. Doing this allows the user to knowingly decide to use a feature of the library that is less safe. Does this sound like a workaround that might work for you?

I should be able to start working on this in a day or two. However, if you want to add this feature yourself tell me so that I can assign this issue to you. 🙂

**Comment by benjamin-cates** [comment]
Oh you're right that the implementation is not necessarily known to the user. I thought it would be a minor change but I can see how it would be confusing, and also the finite difference calculation wouldn't support it either. I think instead of adding it as a feature we could add to the docs that interior mutability requires `RefCell` because adding it as a feature might be additional bloat.

**Comment by AzeezDa** [comment]
Added as documentation to 0.1.3
